// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProofRequest.proto

#ifndef PROTOBUF_INCLUDED_ProofRequest_2eproto
#define PROTOBUF_INCLUDED_ProofRequest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ProofRequest_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_ProofRequest_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_ProofRequest_2eproto();
namespace request_proto {
class Attribute;
class AttributeDefaultTypeInternal;
extern AttributeDefaultTypeInternal _Attribute_default_instance_;
class ContractEvent;
class ContractEventDefaultTypeInternal;
extern ContractEventDefaultTypeInternal _ContractEvent_default_instance_;
class Data;
class DataDefaultTypeInternal;
extern DataDefaultTypeInternal _Data_default_instance_;
class Event;
class EventDefaultTypeInternal;
extern EventDefaultTypeInternal _Event_default_instance_;
class ProofRequest;
class ProofRequestDefaultTypeInternal;
extern ProofRequestDefaultTypeInternal _ProofRequest_default_instance_;
class TxMetaData;
class TxMetaDataDefaultTypeInternal;
extern TxMetaDataDefaultTypeInternal _TxMetaData_default_instance_;
}  // namespace request_proto
namespace google {
namespace protobuf {
template<> ::request_proto::Attribute* Arena::CreateMaybeMessage<::request_proto::Attribute>(Arena*);
template<> ::request_proto::ContractEvent* Arena::CreateMaybeMessage<::request_proto::ContractEvent>(Arena*);
template<> ::request_proto::Data* Arena::CreateMaybeMessage<::request_proto::Data>(Arena*);
template<> ::request_proto::Event* Arena::CreateMaybeMessage<::request_proto::Event>(Arena*);
template<> ::request_proto::ProofRequest* Arena::CreateMaybeMessage<::request_proto::ProofRequest>(Arena*);
template<> ::request_proto::TxMetaData* Arena::CreateMaybeMessage<::request_proto::TxMetaData>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace request_proto {

// ===================================================================

class Attribute :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:request_proto.Attribute) */ {
 public:
  Attribute();
  virtual ~Attribute();

  Attribute(const Attribute& from);

  inline Attribute& operator=(const Attribute& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Attribute(Attribute&& from) noexcept
    : Attribute() {
    *this = ::std::move(from);
  }

  inline Attribute& operator=(Attribute&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Attribute& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Attribute* internal_default_instance() {
    return reinterpret_cast<const Attribute*>(
               &_Attribute_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Attribute* other);
  friend void swap(Attribute& a, Attribute& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Attribute* New() const final {
    return CreateMaybeMessage<Attribute>(nullptr);
  }

  Attribute* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Attribute>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Attribute& from);
  void MergeFrom(const Attribute& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Attribute* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string Key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  #if LANG_CXX11
  void set_key(::std::string&& value);
  #endif
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // string Value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:request_proto.Attribute)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ProofRequest_2eproto;
};
// -------------------------------------------------------------------

class Event :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:request_proto.Event) */ {
 public:
  Event();
  virtual ~Event();

  Event(const Event& from);

  inline Event& operator=(const Event& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Event(Event&& from) noexcept
    : Event() {
    *this = ::std::move(from);
  }

  inline Event& operator=(Event&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Event& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Event* internal_default_instance() {
    return reinterpret_cast<const Event*>(
               &_Event_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Event* other);
  friend void swap(Event& a, Event& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Event* New() const final {
    return CreateMaybeMessage<Event>(nullptr);
  }

  Event* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Event>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Event& from);
  void MergeFrom(const Event& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Event* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .request_proto.Attribute attributes = 2;
  int attributes_size() const;
  void clear_attributes();
  static const int kAttributesFieldNumber = 2;
  ::request_proto::Attribute* mutable_attributes(int index);
  ::google::protobuf::RepeatedPtrField< ::request_proto::Attribute >*
      mutable_attributes();
  const ::request_proto::Attribute& attributes(int index) const;
  ::request_proto::Attribute* add_attributes();
  const ::google::protobuf::RepeatedPtrField< ::request_proto::Attribute >&
      attributes() const;

  // string EventName = 1;
  void clear_eventname();
  static const int kEventNameFieldNumber = 1;
  const ::std::string& eventname() const;
  void set_eventname(const ::std::string& value);
  #if LANG_CXX11
  void set_eventname(::std::string&& value);
  #endif
  void set_eventname(const char* value);
  void set_eventname(const char* value, size_t size);
  ::std::string* mutable_eventname();
  ::std::string* release_eventname();
  void set_allocated_eventname(::std::string* eventname);

  // @@protoc_insertion_point(class_scope:request_proto.Event)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::request_proto::Attribute > attributes_;
  ::google::protobuf::internal::ArenaStringPtr eventname_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ProofRequest_2eproto;
};
// -------------------------------------------------------------------

class ContractEvent :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:request_proto.ContractEvent) */ {
 public:
  ContractEvent();
  virtual ~ContractEvent();

  ContractEvent(const ContractEvent& from);

  inline ContractEvent& operator=(const ContractEvent& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ContractEvent(ContractEvent&& from) noexcept
    : ContractEvent() {
    *this = ::std::move(from);
  }

  inline ContractEvent& operator=(ContractEvent&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ContractEvent& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ContractEvent* internal_default_instance() {
    return reinterpret_cast<const ContractEvent*>(
               &_ContractEvent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(ContractEvent* other);
  friend void swap(ContractEvent& a, ContractEvent& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ContractEvent* New() const final {
    return CreateMaybeMessage<ContractEvent>(nullptr);
  }

  ContractEvent* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ContractEvent>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ContractEvent& from);
  void MergeFrom(const ContractEvent& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ContractEvent* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .request_proto.Event events = 2;
  int events_size() const;
  void clear_events();
  static const int kEventsFieldNumber = 2;
  ::request_proto::Event* mutable_events(int index);
  ::google::protobuf::RepeatedPtrField< ::request_proto::Event >*
      mutable_events();
  const ::request_proto::Event& events(int index) const;
  ::request_proto::Event* add_events();
  const ::google::protobuf::RepeatedPtrField< ::request_proto::Event >&
      events() const;

  // string ContractID = 1;
  void clear_contractid();
  static const int kContractIDFieldNumber = 1;
  const ::std::string& contractid() const;
  void set_contractid(const ::std::string& value);
  #if LANG_CXX11
  void set_contractid(::std::string&& value);
  #endif
  void set_contractid(const char* value);
  void set_contractid(const char* value, size_t size);
  ::std::string* mutable_contractid();
  ::std::string* release_contractid();
  void set_allocated_contractid(::std::string* contractid);

  // @@protoc_insertion_point(class_scope:request_proto.ContractEvent)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::request_proto::Event > events_;
  ::google::protobuf::internal::ArenaStringPtr contractid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ProofRequest_2eproto;
};
// -------------------------------------------------------------------

class TxMetaData :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:request_proto.TxMetaData) */ {
 public:
  TxMetaData();
  virtual ~TxMetaData();

  TxMetaData(const TxMetaData& from);

  inline TxMetaData& operator=(const TxMetaData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TxMetaData(TxMetaData&& from) noexcept
    : TxMetaData() {
    *this = ::std::move(from);
  }

  inline TxMetaData& operator=(TxMetaData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const TxMetaData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TxMetaData* internal_default_instance() {
    return reinterpret_cast<const TxMetaData*>(
               &_TxMetaData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(TxMetaData* other);
  friend void swap(TxMetaData& a, TxMetaData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TxMetaData* New() const final {
    return CreateMaybeMessage<TxMetaData>(nullptr);
  }

  TxMetaData* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TxMetaData>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TxMetaData& from);
  void MergeFrom(const TxMetaData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TxMetaData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes fromAddress = 1;
  void clear_fromaddress();
  static const int kFromAddressFieldNumber = 1;
  const ::std::string& fromaddress() const;
  void set_fromaddress(const ::std::string& value);
  #if LANG_CXX11
  void set_fromaddress(::std::string&& value);
  #endif
  void set_fromaddress(const char* value);
  void set_fromaddress(const void* value, size_t size);
  ::std::string* mutable_fromaddress();
  ::std::string* release_fromaddress();
  void set_allocated_fromaddress(::std::string* fromaddress);

  // bytes ToAddress = 2;
  void clear_toaddress();
  static const int kToAddressFieldNumber = 2;
  const ::std::string& toaddress() const;
  void set_toaddress(const ::std::string& value);
  #if LANG_CXX11
  void set_toaddress(::std::string&& value);
  #endif
  void set_toaddress(const char* value);
  void set_toaddress(const void* value, size_t size);
  ::std::string* mutable_toaddress();
  ::std::string* release_toaddress();
  void set_allocated_toaddress(::std::string* toaddress);

  // uint64 Value = 3;
  void clear_value();
  static const int kValueFieldNumber = 3;
  ::google::protobuf::uint64 value() const;
  void set_value(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:request_proto.TxMetaData)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr fromaddress_;
  ::google::protobuf::internal::ArenaStringPtr toaddress_;
  ::google::protobuf::uint64 value_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ProofRequest_2eproto;
};
// -------------------------------------------------------------------

class Data :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:request_proto.Data) */ {
 public:
  Data();
  virtual ~Data();

  Data(const Data& from);

  inline Data& operator=(const Data& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Data(Data&& from) noexcept
    : Data() {
    *this = ::std::move(from);
  }

  inline Data& operator=(Data&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Data& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Data* internal_default_instance() {
    return reinterpret_cast<const Data*>(
               &_Data_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(Data* other);
  friend void swap(Data& a, Data& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Data* New() const final {
    return CreateMaybeMessage<Data>(nullptr);
  }

  Data* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Data>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Data& from);
  void MergeFrom(const Data& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Data* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .request_proto.ContractEvent events = 2;
  int events_size() const;
  void clear_events();
  static const int kEventsFieldNumber = 2;
  ::request_proto::ContractEvent* mutable_events(int index);
  ::google::protobuf::RepeatedPtrField< ::request_proto::ContractEvent >*
      mutable_events();
  const ::request_proto::ContractEvent& events(int index) const;
  ::request_proto::ContractEvent* add_events();
  const ::google::protobuf::RepeatedPtrField< ::request_proto::ContractEvent >&
      events() const;

  // .request_proto.TxMetaData meta = 1;
  bool has_meta() const;
  void clear_meta();
  static const int kMetaFieldNumber = 1;
  const ::request_proto::TxMetaData& meta() const;
  ::request_proto::TxMetaData* release_meta();
  ::request_proto::TxMetaData* mutable_meta();
  void set_allocated_meta(::request_proto::TxMetaData* meta);

  // @@protoc_insertion_point(class_scope:request_proto.Data)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::request_proto::ContractEvent > events_;
  ::request_proto::TxMetaData* meta_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ProofRequest_2eproto;
};
// -------------------------------------------------------------------

class ProofRequest :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:request_proto.ProofRequest) */ {
 public:
  ProofRequest();
  virtual ~ProofRequest();

  ProofRequest(const ProofRequest& from);

  inline ProofRequest& operator=(const ProofRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ProofRequest(ProofRequest&& from) noexcept
    : ProofRequest() {
    *this = ::std::move(from);
  }

  inline ProofRequest& operator=(ProofRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ProofRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ProofRequest* internal_default_instance() {
    return reinterpret_cast<const ProofRequest*>(
               &_ProofRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(ProofRequest* other);
  friend void swap(ProofRequest& a, ProofRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ProofRequest* New() const final {
    return CreateMaybeMessage<ProofRequest>(nullptr);
  }

  ProofRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ProofRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ProofRequest& from);
  void MergeFrom(const ProofRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProofRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string ChainType = 1;
  void clear_chaintype();
  static const int kChainTypeFieldNumber = 1;
  const ::std::string& chaintype() const;
  void set_chaintype(const ::std::string& value);
  #if LANG_CXX11
  void set_chaintype(::std::string&& value);
  #endif
  void set_chaintype(const char* value);
  void set_chaintype(const char* value, size_t size);
  ::std::string* mutable_chaintype();
  ::std::string* release_chaintype();
  void set_allocated_chaintype(::std::string* chaintype);

  // string ChainID = 2;
  void clear_chainid();
  static const int kChainIDFieldNumber = 2;
  const ::std::string& chainid() const;
  void set_chainid(const ::std::string& value);
  #if LANG_CXX11
  void set_chainid(::std::string&& value);
  #endif
  void set_chainid(const char* value);
  void set_chainid(const char* value, size_t size);
  ::std::string* mutable_chainid();
  ::std::string* release_chainid();
  void set_allocated_chainid(::std::string* chainid);

  // bytes TxHash = 4;
  void clear_txhash();
  static const int kTxHashFieldNumber = 4;
  const ::std::string& txhash() const;
  void set_txhash(const ::std::string& value);
  #if LANG_CXX11
  void set_txhash(::std::string&& value);
  #endif
  void set_txhash(const char* value);
  void set_txhash(const void* value, size_t size);
  ::std::string* mutable_txhash();
  ::std::string* release_txhash();
  void set_allocated_txhash(::std::string* txhash);

  // bytes OriginalData = 7;
  void clear_originaldata();
  static const int kOriginalDataFieldNumber = 7;
  const ::std::string& originaldata() const;
  void set_originaldata(const ::std::string& value);
  #if LANG_CXX11
  void set_originaldata(::std::string&& value);
  #endif
  void set_originaldata(const char* value);
  void set_originaldata(const void* value, size_t size);
  ::std::string* mutable_originaldata();
  ::std::string* release_originaldata();
  void set_allocated_originaldata(::std::string* originaldata);

  // .request_proto.Data Data = 3;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 3;
  const ::request_proto::Data& data() const;
  ::request_proto::Data* release_data();
  ::request_proto::Data* mutable_data();
  void set_allocated_data(::request_proto::Data* data);

  // uint64 Height = 5;
  void clear_height();
  static const int kHeightFieldNumber = 5;
  ::google::protobuf::uint64 height() const;
  void set_height(::google::protobuf::uint64 value);

  // uint64 TxIndex = 6;
  void clear_txindex();
  static const int kTxIndexFieldNumber = 6;
  ::google::protobuf::uint64 txindex() const;
  void set_txindex(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:request_proto.ProofRequest)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr chaintype_;
  ::google::protobuf::internal::ArenaStringPtr chainid_;
  ::google::protobuf::internal::ArenaStringPtr txhash_;
  ::google::protobuf::internal::ArenaStringPtr originaldata_;
  ::request_proto::Data* data_;
  ::google::protobuf::uint64 height_;
  ::google::protobuf::uint64 txindex_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ProofRequest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Attribute

// string Key = 1;
inline void Attribute::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Attribute::key() const {
  // @@protoc_insertion_point(field_get:request_proto.Attribute.Key)
  return key_.GetNoArena();
}
inline void Attribute::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:request_proto.Attribute.Key)
}
#if LANG_CXX11
inline void Attribute::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:request_proto.Attribute.Key)
}
#endif
inline void Attribute::set_key(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:request_proto.Attribute.Key)
}
inline void Attribute::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:request_proto.Attribute.Key)
}
inline ::std::string* Attribute::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:request_proto.Attribute.Key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Attribute::release_key() {
  // @@protoc_insertion_point(field_release:request_proto.Attribute.Key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Attribute::set_allocated_key(::std::string* key) {
  if (key != nullptr) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:request_proto.Attribute.Key)
}

// string Value = 2;
inline void Attribute::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Attribute::value() const {
  // @@protoc_insertion_point(field_get:request_proto.Attribute.Value)
  return value_.GetNoArena();
}
inline void Attribute::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:request_proto.Attribute.Value)
}
#if LANG_CXX11
inline void Attribute::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:request_proto.Attribute.Value)
}
#endif
inline void Attribute::set_value(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:request_proto.Attribute.Value)
}
inline void Attribute::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:request_proto.Attribute.Value)
}
inline ::std::string* Attribute::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:request_proto.Attribute.Value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Attribute::release_value() {
  // @@protoc_insertion_point(field_release:request_proto.Attribute.Value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Attribute::set_allocated_value(::std::string* value) {
  if (value != nullptr) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:request_proto.Attribute.Value)
}

// -------------------------------------------------------------------

// Event

// string EventName = 1;
inline void Event::clear_eventname() {
  eventname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Event::eventname() const {
  // @@protoc_insertion_point(field_get:request_proto.Event.EventName)
  return eventname_.GetNoArena();
}
inline void Event::set_eventname(const ::std::string& value) {
  
  eventname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:request_proto.Event.EventName)
}
#if LANG_CXX11
inline void Event::set_eventname(::std::string&& value) {
  
  eventname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:request_proto.Event.EventName)
}
#endif
inline void Event::set_eventname(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  eventname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:request_proto.Event.EventName)
}
inline void Event::set_eventname(const char* value, size_t size) {
  
  eventname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:request_proto.Event.EventName)
}
inline ::std::string* Event::mutable_eventname() {
  
  // @@protoc_insertion_point(field_mutable:request_proto.Event.EventName)
  return eventname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Event::release_eventname() {
  // @@protoc_insertion_point(field_release:request_proto.Event.EventName)
  
  return eventname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Event::set_allocated_eventname(::std::string* eventname) {
  if (eventname != nullptr) {
    
  } else {
    
  }
  eventname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), eventname);
  // @@protoc_insertion_point(field_set_allocated:request_proto.Event.EventName)
}

// repeated .request_proto.Attribute attributes = 2;
inline int Event::attributes_size() const {
  return attributes_.size();
}
inline void Event::clear_attributes() {
  attributes_.Clear();
}
inline ::request_proto::Attribute* Event::mutable_attributes(int index) {
  // @@protoc_insertion_point(field_mutable:request_proto.Event.attributes)
  return attributes_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::request_proto::Attribute >*
Event::mutable_attributes() {
  // @@protoc_insertion_point(field_mutable_list:request_proto.Event.attributes)
  return &attributes_;
}
inline const ::request_proto::Attribute& Event::attributes(int index) const {
  // @@protoc_insertion_point(field_get:request_proto.Event.attributes)
  return attributes_.Get(index);
}
inline ::request_proto::Attribute* Event::add_attributes() {
  // @@protoc_insertion_point(field_add:request_proto.Event.attributes)
  return attributes_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::request_proto::Attribute >&
Event::attributes() const {
  // @@protoc_insertion_point(field_list:request_proto.Event.attributes)
  return attributes_;
}

// -------------------------------------------------------------------

// ContractEvent

// string ContractID = 1;
inline void ContractEvent::clear_contractid() {
  contractid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ContractEvent::contractid() const {
  // @@protoc_insertion_point(field_get:request_proto.ContractEvent.ContractID)
  return contractid_.GetNoArena();
}
inline void ContractEvent::set_contractid(const ::std::string& value) {
  
  contractid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:request_proto.ContractEvent.ContractID)
}
#if LANG_CXX11
inline void ContractEvent::set_contractid(::std::string&& value) {
  
  contractid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:request_proto.ContractEvent.ContractID)
}
#endif
inline void ContractEvent::set_contractid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  contractid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:request_proto.ContractEvent.ContractID)
}
inline void ContractEvent::set_contractid(const char* value, size_t size) {
  
  contractid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:request_proto.ContractEvent.ContractID)
}
inline ::std::string* ContractEvent::mutable_contractid() {
  
  // @@protoc_insertion_point(field_mutable:request_proto.ContractEvent.ContractID)
  return contractid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ContractEvent::release_contractid() {
  // @@protoc_insertion_point(field_release:request_proto.ContractEvent.ContractID)
  
  return contractid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ContractEvent::set_allocated_contractid(::std::string* contractid) {
  if (contractid != nullptr) {
    
  } else {
    
  }
  contractid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), contractid);
  // @@protoc_insertion_point(field_set_allocated:request_proto.ContractEvent.ContractID)
}

// repeated .request_proto.Event events = 2;
inline int ContractEvent::events_size() const {
  return events_.size();
}
inline void ContractEvent::clear_events() {
  events_.Clear();
}
inline ::request_proto::Event* ContractEvent::mutable_events(int index) {
  // @@protoc_insertion_point(field_mutable:request_proto.ContractEvent.events)
  return events_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::request_proto::Event >*
ContractEvent::mutable_events() {
  // @@protoc_insertion_point(field_mutable_list:request_proto.ContractEvent.events)
  return &events_;
}
inline const ::request_proto::Event& ContractEvent::events(int index) const {
  // @@protoc_insertion_point(field_get:request_proto.ContractEvent.events)
  return events_.Get(index);
}
inline ::request_proto::Event* ContractEvent::add_events() {
  // @@protoc_insertion_point(field_add:request_proto.ContractEvent.events)
  return events_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::request_proto::Event >&
ContractEvent::events() const {
  // @@protoc_insertion_point(field_list:request_proto.ContractEvent.events)
  return events_;
}

// -------------------------------------------------------------------

// TxMetaData

// bytes fromAddress = 1;
inline void TxMetaData::clear_fromaddress() {
  fromaddress_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TxMetaData::fromaddress() const {
  // @@protoc_insertion_point(field_get:request_proto.TxMetaData.fromAddress)
  return fromaddress_.GetNoArena();
}
inline void TxMetaData::set_fromaddress(const ::std::string& value) {
  
  fromaddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:request_proto.TxMetaData.fromAddress)
}
#if LANG_CXX11
inline void TxMetaData::set_fromaddress(::std::string&& value) {
  
  fromaddress_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:request_proto.TxMetaData.fromAddress)
}
#endif
inline void TxMetaData::set_fromaddress(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  fromaddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:request_proto.TxMetaData.fromAddress)
}
inline void TxMetaData::set_fromaddress(const void* value, size_t size) {
  
  fromaddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:request_proto.TxMetaData.fromAddress)
}
inline ::std::string* TxMetaData::mutable_fromaddress() {
  
  // @@protoc_insertion_point(field_mutable:request_proto.TxMetaData.fromAddress)
  return fromaddress_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TxMetaData::release_fromaddress() {
  // @@protoc_insertion_point(field_release:request_proto.TxMetaData.fromAddress)
  
  return fromaddress_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TxMetaData::set_allocated_fromaddress(::std::string* fromaddress) {
  if (fromaddress != nullptr) {
    
  } else {
    
  }
  fromaddress_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), fromaddress);
  // @@protoc_insertion_point(field_set_allocated:request_proto.TxMetaData.fromAddress)
}

// bytes ToAddress = 2;
inline void TxMetaData::clear_toaddress() {
  toaddress_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TxMetaData::toaddress() const {
  // @@protoc_insertion_point(field_get:request_proto.TxMetaData.ToAddress)
  return toaddress_.GetNoArena();
}
inline void TxMetaData::set_toaddress(const ::std::string& value) {
  
  toaddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:request_proto.TxMetaData.ToAddress)
}
#if LANG_CXX11
inline void TxMetaData::set_toaddress(::std::string&& value) {
  
  toaddress_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:request_proto.TxMetaData.ToAddress)
}
#endif
inline void TxMetaData::set_toaddress(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  toaddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:request_proto.TxMetaData.ToAddress)
}
inline void TxMetaData::set_toaddress(const void* value, size_t size) {
  
  toaddress_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:request_proto.TxMetaData.ToAddress)
}
inline ::std::string* TxMetaData::mutable_toaddress() {
  
  // @@protoc_insertion_point(field_mutable:request_proto.TxMetaData.ToAddress)
  return toaddress_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TxMetaData::release_toaddress() {
  // @@protoc_insertion_point(field_release:request_proto.TxMetaData.ToAddress)
  
  return toaddress_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TxMetaData::set_allocated_toaddress(::std::string* toaddress) {
  if (toaddress != nullptr) {
    
  } else {
    
  }
  toaddress_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), toaddress);
  // @@protoc_insertion_point(field_set_allocated:request_proto.TxMetaData.ToAddress)
}

// uint64 Value = 3;
inline void TxMetaData::clear_value() {
  value_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 TxMetaData::value() const {
  // @@protoc_insertion_point(field_get:request_proto.TxMetaData.Value)
  return value_;
}
inline void TxMetaData::set_value(::google::protobuf::uint64 value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:request_proto.TxMetaData.Value)
}

// -------------------------------------------------------------------

// Data

// .request_proto.TxMetaData meta = 1;
inline bool Data::has_meta() const {
  return this != internal_default_instance() && meta_ != nullptr;
}
inline void Data::clear_meta() {
  if (GetArenaNoVirtual() == nullptr && meta_ != nullptr) {
    delete meta_;
  }
  meta_ = nullptr;
}
inline const ::request_proto::TxMetaData& Data::meta() const {
  const ::request_proto::TxMetaData* p = meta_;
  // @@protoc_insertion_point(field_get:request_proto.Data.meta)
  return p != nullptr ? *p : *reinterpret_cast<const ::request_proto::TxMetaData*>(
      &::request_proto::_TxMetaData_default_instance_);
}
inline ::request_proto::TxMetaData* Data::release_meta() {
  // @@protoc_insertion_point(field_release:request_proto.Data.meta)
  
  ::request_proto::TxMetaData* temp = meta_;
  meta_ = nullptr;
  return temp;
}
inline ::request_proto::TxMetaData* Data::mutable_meta() {
  
  if (meta_ == nullptr) {
    auto* p = CreateMaybeMessage<::request_proto::TxMetaData>(GetArenaNoVirtual());
    meta_ = p;
  }
  // @@protoc_insertion_point(field_mutable:request_proto.Data.meta)
  return meta_;
}
inline void Data::set_allocated_meta(::request_proto::TxMetaData* meta) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete meta_;
  }
  if (meta) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      meta = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, meta, submessage_arena);
    }
    
  } else {
    
  }
  meta_ = meta;
  // @@protoc_insertion_point(field_set_allocated:request_proto.Data.meta)
}

// repeated .request_proto.ContractEvent events = 2;
inline int Data::events_size() const {
  return events_.size();
}
inline void Data::clear_events() {
  events_.Clear();
}
inline ::request_proto::ContractEvent* Data::mutable_events(int index) {
  // @@protoc_insertion_point(field_mutable:request_proto.Data.events)
  return events_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::request_proto::ContractEvent >*
Data::mutable_events() {
  // @@protoc_insertion_point(field_mutable_list:request_proto.Data.events)
  return &events_;
}
inline const ::request_proto::ContractEvent& Data::events(int index) const {
  // @@protoc_insertion_point(field_get:request_proto.Data.events)
  return events_.Get(index);
}
inline ::request_proto::ContractEvent* Data::add_events() {
  // @@protoc_insertion_point(field_add:request_proto.Data.events)
  return events_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::request_proto::ContractEvent >&
Data::events() const {
  // @@protoc_insertion_point(field_list:request_proto.Data.events)
  return events_;
}

// -------------------------------------------------------------------

// ProofRequest

// string ChainType = 1;
inline void ProofRequest::clear_chaintype() {
  chaintype_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ProofRequest::chaintype() const {
  // @@protoc_insertion_point(field_get:request_proto.ProofRequest.ChainType)
  return chaintype_.GetNoArena();
}
inline void ProofRequest::set_chaintype(const ::std::string& value) {
  
  chaintype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:request_proto.ProofRequest.ChainType)
}
#if LANG_CXX11
inline void ProofRequest::set_chaintype(::std::string&& value) {
  
  chaintype_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:request_proto.ProofRequest.ChainType)
}
#endif
inline void ProofRequest::set_chaintype(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  chaintype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:request_proto.ProofRequest.ChainType)
}
inline void ProofRequest::set_chaintype(const char* value, size_t size) {
  
  chaintype_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:request_proto.ProofRequest.ChainType)
}
inline ::std::string* ProofRequest::mutable_chaintype() {
  
  // @@protoc_insertion_point(field_mutable:request_proto.ProofRequest.ChainType)
  return chaintype_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ProofRequest::release_chaintype() {
  // @@protoc_insertion_point(field_release:request_proto.ProofRequest.ChainType)
  
  return chaintype_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ProofRequest::set_allocated_chaintype(::std::string* chaintype) {
  if (chaintype != nullptr) {
    
  } else {
    
  }
  chaintype_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), chaintype);
  // @@protoc_insertion_point(field_set_allocated:request_proto.ProofRequest.ChainType)
}

// string ChainID = 2;
inline void ProofRequest::clear_chainid() {
  chainid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ProofRequest::chainid() const {
  // @@protoc_insertion_point(field_get:request_proto.ProofRequest.ChainID)
  return chainid_.GetNoArena();
}
inline void ProofRequest::set_chainid(const ::std::string& value) {
  
  chainid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:request_proto.ProofRequest.ChainID)
}
#if LANG_CXX11
inline void ProofRequest::set_chainid(::std::string&& value) {
  
  chainid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:request_proto.ProofRequest.ChainID)
}
#endif
inline void ProofRequest::set_chainid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  chainid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:request_proto.ProofRequest.ChainID)
}
inline void ProofRequest::set_chainid(const char* value, size_t size) {
  
  chainid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:request_proto.ProofRequest.ChainID)
}
inline ::std::string* ProofRequest::mutable_chainid() {
  
  // @@protoc_insertion_point(field_mutable:request_proto.ProofRequest.ChainID)
  return chainid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ProofRequest::release_chainid() {
  // @@protoc_insertion_point(field_release:request_proto.ProofRequest.ChainID)
  
  return chainid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ProofRequest::set_allocated_chainid(::std::string* chainid) {
  if (chainid != nullptr) {
    
  } else {
    
  }
  chainid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), chainid);
  // @@protoc_insertion_point(field_set_allocated:request_proto.ProofRequest.ChainID)
}

// .request_proto.Data Data = 3;
inline bool ProofRequest::has_data() const {
  return this != internal_default_instance() && data_ != nullptr;
}
inline void ProofRequest::clear_data() {
  if (GetArenaNoVirtual() == nullptr && data_ != nullptr) {
    delete data_;
  }
  data_ = nullptr;
}
inline const ::request_proto::Data& ProofRequest::data() const {
  const ::request_proto::Data* p = data_;
  // @@protoc_insertion_point(field_get:request_proto.ProofRequest.Data)
  return p != nullptr ? *p : *reinterpret_cast<const ::request_proto::Data*>(
      &::request_proto::_Data_default_instance_);
}
inline ::request_proto::Data* ProofRequest::release_data() {
  // @@protoc_insertion_point(field_release:request_proto.ProofRequest.Data)
  
  ::request_proto::Data* temp = data_;
  data_ = nullptr;
  return temp;
}
inline ::request_proto::Data* ProofRequest::mutable_data() {
  
  if (data_ == nullptr) {
    auto* p = CreateMaybeMessage<::request_proto::Data>(GetArenaNoVirtual());
    data_ = p;
  }
  // @@protoc_insertion_point(field_mutable:request_proto.ProofRequest.Data)
  return data_;
}
inline void ProofRequest::set_allocated_data(::request_proto::Data* data) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete data_;
  }
  if (data) {
    ::google::protobuf::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      data = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, data, submessage_arena);
    }
    
  } else {
    
  }
  data_ = data;
  // @@protoc_insertion_point(field_set_allocated:request_proto.ProofRequest.Data)
}

// bytes TxHash = 4;
inline void ProofRequest::clear_txhash() {
  txhash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ProofRequest::txhash() const {
  // @@protoc_insertion_point(field_get:request_proto.ProofRequest.TxHash)
  return txhash_.GetNoArena();
}
inline void ProofRequest::set_txhash(const ::std::string& value) {
  
  txhash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:request_proto.ProofRequest.TxHash)
}
#if LANG_CXX11
inline void ProofRequest::set_txhash(::std::string&& value) {
  
  txhash_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:request_proto.ProofRequest.TxHash)
}
#endif
inline void ProofRequest::set_txhash(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  txhash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:request_proto.ProofRequest.TxHash)
}
inline void ProofRequest::set_txhash(const void* value, size_t size) {
  
  txhash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:request_proto.ProofRequest.TxHash)
}
inline ::std::string* ProofRequest::mutable_txhash() {
  
  // @@protoc_insertion_point(field_mutable:request_proto.ProofRequest.TxHash)
  return txhash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ProofRequest::release_txhash() {
  // @@protoc_insertion_point(field_release:request_proto.ProofRequest.TxHash)
  
  return txhash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ProofRequest::set_allocated_txhash(::std::string* txhash) {
  if (txhash != nullptr) {
    
  } else {
    
  }
  txhash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), txhash);
  // @@protoc_insertion_point(field_set_allocated:request_proto.ProofRequest.TxHash)
}

// uint64 Height = 5;
inline void ProofRequest::clear_height() {
  height_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ProofRequest::height() const {
  // @@protoc_insertion_point(field_get:request_proto.ProofRequest.Height)
  return height_;
}
inline void ProofRequest::set_height(::google::protobuf::uint64 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:request_proto.ProofRequest.Height)
}

// uint64 TxIndex = 6;
inline void ProofRequest::clear_txindex() {
  txindex_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ProofRequest::txindex() const {
  // @@protoc_insertion_point(field_get:request_proto.ProofRequest.TxIndex)
  return txindex_;
}
inline void ProofRequest::set_txindex(::google::protobuf::uint64 value) {
  
  txindex_ = value;
  // @@protoc_insertion_point(field_set:request_proto.ProofRequest.TxIndex)
}

// bytes OriginalData = 7;
inline void ProofRequest::clear_originaldata() {
  originaldata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ProofRequest::originaldata() const {
  // @@protoc_insertion_point(field_get:request_proto.ProofRequest.OriginalData)
  return originaldata_.GetNoArena();
}
inline void ProofRequest::set_originaldata(const ::std::string& value) {
  
  originaldata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:request_proto.ProofRequest.OriginalData)
}
#if LANG_CXX11
inline void ProofRequest::set_originaldata(::std::string&& value) {
  
  originaldata_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:request_proto.ProofRequest.OriginalData)
}
#endif
inline void ProofRequest::set_originaldata(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  originaldata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:request_proto.ProofRequest.OriginalData)
}
inline void ProofRequest::set_originaldata(const void* value, size_t size) {
  
  originaldata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:request_proto.ProofRequest.OriginalData)
}
inline ::std::string* ProofRequest::mutable_originaldata() {
  
  // @@protoc_insertion_point(field_mutable:request_proto.ProofRequest.OriginalData)
  return originaldata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ProofRequest::release_originaldata() {
  // @@protoc_insertion_point(field_release:request_proto.ProofRequest.OriginalData)
  
  return originaldata_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ProofRequest::set_allocated_originaldata(::std::string* originaldata) {
  if (originaldata != nullptr) {
    
  } else {
    
  }
  originaldata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), originaldata);
  // @@protoc_insertion_point(field_set_allocated:request_proto.ProofRequest.OriginalData)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace request_proto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_ProofRequest_2eproto
