version: '2'

networks:
  compliance-engine:
    driver: bridge

services:
  mysql-compliance-engine:
    container_name: mysql-compliance-engine
    image: mysql:latest
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 33006:3306
    networks: 
      - compliance-engine
      
  compliance-engine:
    container_name: compliance-engine-exec
    image: compliance-engine:latest
    depends_on: 
      - mysql-compliance-engine
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}
      - CORE_MYSQL_ADDRESS=mysql-compliance-engine:3306
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - MYSQL_ROOT_PASSWORD=123456
    working_dir: /root/compliance-engine/build
    command: >
      /bin/bash -c '
      sleep 20

      echo "waited database end!";
      ./main --log ../logs/compliance_engine.log --config ../config/ComplianceEngine.yaml
      '
    ports:
      - 50051:50051
    networks: 
      - compliance-engine
