// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Register.proto

#include "Register.pb.h"
#include "Register.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace request_proto {

static const char* Register_method_names[] = {
  "/request_proto.Register/RegisterRegulatoryService",
};

std::unique_ptr< Register::Stub> Register::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Register::Stub> stub(new Register::Stub(channel));
  return stub;
}

Register::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_RegisterRegulatoryService_(Register_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Register::Stub::RegisterRegulatoryService(::grpc::ClientContext* context, const ::request_proto::RegisterRequest& request, ::request_proto::RegisterResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::request_proto::RegisterRequest, ::request_proto::RegisterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RegisterRegulatoryService_, context, request, response);
}

void Register::Stub::experimental_async::RegisterRegulatoryService(::grpc::ClientContext* context, const ::request_proto::RegisterRequest* request, ::request_proto::RegisterResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::request_proto::RegisterRequest, ::request_proto::RegisterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterRegulatoryService_, context, request, response, std::move(f));
}

void Register::Stub::experimental_async::RegisterRegulatoryService(::grpc::ClientContext* context, const ::request_proto::RegisterRequest* request, ::request_proto::RegisterResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RegisterRegulatoryService_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::request_proto::RegisterResponse>* Register::Stub::PrepareAsyncRegisterRegulatoryServiceRaw(::grpc::ClientContext* context, const ::request_proto::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::request_proto::RegisterResponse, ::request_proto::RegisterRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RegisterRegulatoryService_, context, request);
}

::grpc::ClientAsyncResponseReader< ::request_proto::RegisterResponse>* Register::Stub::AsyncRegisterRegulatoryServiceRaw(::grpc::ClientContext* context, const ::request_proto::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterRegulatoryServiceRaw(context, request, cq);
  result->StartCall();
  return result;
}

Register::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Register_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Register::Service, ::request_proto::RegisterRequest, ::request_proto::RegisterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Register::Service* service,
             ::grpc::ServerContext* ctx,
             const ::request_proto::RegisterRequest* req,
             ::request_proto::RegisterResponse* resp) {
               return service->RegisterRegulatoryService(ctx, req, resp);
             }, this)));
}

Register::Service::~Service() {
}

::grpc::Status Register::Service::RegisterRegulatoryService(::grpc::ServerContext* context, const ::request_proto::RegisterRequest* request, ::request_proto::RegisterResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace request_proto

